### ISSUE TITLE
Build Locutus fail

### ISSUE THREAD

**Issue by wzhrj1234** [bmnielsen/Locutus#1]
Hi. There are some problems when I build Locutus. Visual Studio Ultimate 2013 Update 5, BWAPI 4.1.2, BWTA 2.2 are used to build Locutus. When building,  I get the following error:

2>  Block.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
2>LINK : fatal error C1047: The object or library file 'D:\Locutus\Locutus-master\Steamhammer\VisualStudio\\Release\Locutus\Block.obj' was created with an older compiler than other objects; rebuild old objects and libraries
2>LINK : fatal error LNK1257: code generation failed
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

I google the error and someone say it will be solved if I close Whole Program Optimization. After closing Whole Program Optimization, I get another error:

2>LINK : fatal error C1900: Il mismatch between 'P1' version '20150812' and 'P2' version '20100826'
2>LINK : fatal error LNK1257: code generation failed

The solutions from google is closing Whole Program Optimization also or update vs ( But my vs2013 is Update 5 already). 
What's wrong with the codes? Or can you send me the built dll of Locutus? Thank you!

**Comment by bmnielsen** [comment]
Hi,

First off sorry for the delay, Github didn't alert me about your issue :(

I've only used Visual Studio 2017 to build it, so I'm not sure what is needed to get it to build in VS2013. I know people using VS2017 with BWAPI 4.2.0 have seen similar issues when the BWAPI libraries are built with an older compiler version, so perhaps you've run into something similar with VS2013 and BWAPI 4.1.2.

If you just want the bot binaries, you should always be able to find the newest version on the bot's profile page on SSCAIT: https://sscaitournament.com/index.php?action=botDetails&bot=Locutus (there's a "bot binary" link at the bottom).

Hope this helps,
Bruce
