### ISSUE TITLE
I want to use Locutus extension Terran, whether can play AIIDE2019?

### ISSUE THREAD

**Issue by liongis** [bmnielsen/Locutus#3]
It's nice to see you write so much code for StarCraft 1 AI, i can feel the love and thought stake in StarCraft and AI by reading your code, I'm also a god player, and the previous DaQin was based on the Locutus improvements, And I noticed that after taking part in last year's AIIDE competition, you modified the license. To avoid and you write the God AI is different, I want to develop the human AI, I think the human family is a long-range attack unit, in the tactical advantage. People based on the latest version of Locutus development do not know if they can participate in the AIIDE2019 competition?

**Comment by bmnielsen** [comment]
Hello,

If I understand correctly, you want to create a fork of Locutus that plays Terran. If so, then yes, you may use the current source of Locutus as the basis for a Terran bot and submit it to StarCraft AI tournaments such as AIIDE 2019.

Be aware that I have not considered Terran (or Zerg for that matter) when making any of my changes from my original fork of Steamhammer, so I expect there will be many things that don't work correctly.

Good luck!
Bruce

**Comment by liongis** [comment]
感谢你的同意！我在修改一些代码的结构，希望Locutus更容易进行三个种族的开发，也可以让更多的人使用Locutus参于星际争霸AI的开发。

**Comment by liongis** [comment]
Thanks for agreeing! In the structure of modified some code, I hope Locutus easier to the development of the Terran, and Zerg, also can let more people to use Locutus participate in development of starcraft AI. Thanks again for your open source spirit.
